// <auto-generated />
using System;
using CourseApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseApi.Migrations
{
    [DbContext(typeof(myAppDbContext))]
    [Migration("20221019071607_m")]
    partial class m
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseApi.Models.Entity.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoursePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstituteId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CourseId");

                    b.HasIndex("InstituteId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseApi.Models.Entity.Institute", b =>
                {
                    b.Property<int>("InstituteId")
                        .HasColumnType("int");

                    b.Property<string>("InstituteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutephotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteId");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("CourseApi.Models.Entity.Course", b =>
                {
                    b.HasOne("CourseApi.Models.Entity.Institute", "Institute")
                        .WithMany("Courses")
                        .HasForeignKey("InstituteId");

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("CourseApi.Models.Entity.Institute", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
